services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3001"
  #   networks:
  #     - appnetwork
  #   depends_on:
  #     - redis
  #     - mongodb
  #   env_file:
  #     - ./env/.env.production
  
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - appnetwork
  
  mongodb:
    container_name: mongodb_with_volume
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge

volumes:
  mongo_data:
